### ISSUE TITLE
meta文件

### ISSUE THREAD

**Issue by nanhaishiyounan** [PaperStar/paper-star#1]
![image](https://user-images.githubusercontent.com/24801059/57422396-7c47d080-7242-11e9-9fb8-38c540e39c43.png)
你好，你这两个文件的meta不匹配，能否看下，我学习一下你的代码，大佬

**Comment by YunYouJun** [comment]
能否请问一下您的 Cocos Creator 的版本?以及提示的报错信息。
当前 master 分支是打算升级到 2.x 的版本，但还在进行中，没有完成，下个月有空会继续开发。
分支里 v1.0.0 是原先 Cocos Creator 1.x 版本可以正常运行的版本。

**Comment by nanhaishiyounan** [comment]
> 能否请问一下您的 Cocos Creator 的版本?以及提示的报错信息。
> 当前 master 分支是打算升级到 2.x 的版本，但还在进行中，没有完成，下个月有空会继续开发。
> 分支里 v1.0.0 是原先 Cocos Creator 1.x 版本可以正常运行的版本。

我的是2.0.9，好的，那我试下1.x，报错就是.meta匹配不到资源，所以无法运行，自动把.meta文件删除备份，倒不是代码里的问题

**Comment by nanhaishiyounan** [comment]
![image](https://user-images.githubusercontent.com/24801059/57422905-6e934a80-7244-11e9-89a4-faffb36102e6.png)
这个.meta和文件对应不起来，是上传漏掉了？

**Comment by YunYouJun** [comment]
我明白了，`Prefab/Scene` 和 `Script/plugins` 是我预留的空文件夹目录结构，git 上传文件时会自动忽略空文件夹。但是 Cocos Creator 自动生成了空文件夹的 `.meta` 标识，所以被上传上去了。
所以把这两个 `.meta` 直接删掉就可以，没什么影响。
感谢您的提醒，之后开发时再补充文件夹内容就可以修复。
